"""Add reconciliation_run_id to exceptions

Revision ID: dce40eeb7d7f
Revises: dd7df5dbeb77
Create Date: 2026-09-10 01:40:40.039296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce40eeb7d7f'
down_revision: Union[str, Sequence[str], None] = 'dd7df5dbeb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exceptions', sa.Column('reconciliation_run_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'exceptions', 'reconciliation_runs', ['reconciliation_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exceptions', type_='foreignkey')
    op.drop_column('exceptions', 'reconciliation_run_id')
    # ### end Alembic commands ###
